[keyswap]
S-2 = "@"
S-6 = "^"
S-7 = "&"
S-8 = "*"
S-9 = "("
S-0 = ")"
S-- = "_"
"^" = "="
"S-^" = "+"
"@" = "["
"S-@" = "{"
"[" = "]"
"S-[" = "}"
"S-;" = ":"
":" = "'"
"S-:" = '"'
"]" = "`"
"S-]" = "~"
Ro = "_"
