[targets.emacs_like_app]
app = 're:(?i)^(emacs|runemacs|WindowsTerminal|wezterm-gui|alacritty|mintty)\.exe$'

[targets.non_emacs_app]
not = "emacs_like_app"

[targets.redo_with_ctrl_shift_z]
app = 're:(?i)^(Photoshop|Illustrator|AfterFX|blender|gimp-[\d.]+|inkscape|Figma|idea64|pycharm64|webstorm64|rider64|clion64|goland64|rustrover64|phpstorm64|datagrip64)\.exe$'

[targets.explorer]
app = "explorer.exe"

[targets.notepad]
app = "notepad.exe"

[targets.vscode]
app = "Code.exe"

[targets.jetbrains]
app = 're:(?i)^(idea64|pycharm64|webstorm64|rider64|clion64|goland64|rustrover64|phpstorm64|datagrip64)\.exe$'

[actions]
forward_char = { non_emacs_app = "Right" }
backward_char = { non_emacs_app = "Left" }
next_line = { non_emacs_app = "Down" }
previous_line = { non_emacs_app = "Up" }
beginning_of_line = { non_emacs_app = "Home" }
end_of_line = { non_emacs_app = "End" }
delete_backward_char = { non_emacs_app = "Backspace" }
delete_char = { non_emacs_app = "Delete" }
forward_word = { non_emacs_app = "C-Right" }
backward_word = { non_emacs_app = "C-Left" }
beginning_of_buffer = { non_emacs_app = "C-Home" }
end_of_buffer = { non_emacs_app = "C-End" }
scroll_up = { non_emacs_app = "PageDown" }
scroll_down = { non_emacs_app = "PageUp" }
newline = { non_emacs_app = "Enter" }
kill_line = { non_emacs_app = "S-End C-x" }
kill_whole_line = { non_emacs_app = "Home S-Down C-x" }
copy_whole_line = { non_emacs_app = "Home S-Down C-c Left" }
kill_word = { non_emacs_app = "C-S-Right C-x" }
backward_kill_word = { non_emacs_app = "C-S-Left C-x" }
kill_region = { non_emacs_app = "C-x" }
kill_ring_save = { non_emacs_app = "C-c" }
yank = { non_emacs_app = "C-v" }
undo = { non_emacs_app = "C-z" }
redo = { redo_with_ctrl_shift_z = "C-S-z", non_emacs_app = "C-y" }
select_forward_char = { non_emacs_app = "S-Right" }
select_backward_char = { non_emacs_app = "S-Left" }
select_next_line = { non_emacs_app = "S-Down" }
select_previous_line = { non_emacs_app = "S-Up" }
select_beginning_of_line = { non_emacs_app = "S-Home" }
select_end_of_line = { non_emacs_app = "S-End" }
select_forward_word = { non_emacs_app = "C-S-Right" }
select_backward_word = { non_emacs_app = "C-S-Left" }
select_beginning_of_buffer = { non_emacs_app = "C-S-Home" }
select_end_of_buffer = { non_emacs_app = "C-S-End" }
select_all = "C-a"
save = "C-s"
save_as = "C-S-s"
close_document = "C-w"
open_file = "C-o"
quit_app = "M-F4"
search_forward = "C-f"
search_next = "F3"
search_previous = "S-F3"
new_tab = "C-t"
next_tab = "C-Tab"
previous_tab = "C-S-Tab"
switch_app = "M-Tab"
switch_app_back = "M-S-Tab"
execute_extended_command = [{ input = "M-x", position = "bottom" }]
previous_desktop = "W-C-Left"
next_desktop = "W-C-Right"
task_view = "W-Tab"
show_desktop = "W-d"
screenshot = "W-S-s"
keyboard_quit = { non_emacs_app = "Esc" }
open_line = { non_emacs_app = "Enter Left" }
save_all = { notepad = "C-M-s" }
replace = { notepad = "C-h" }
recent_files = { vscode = "C-r", jetbrains = "C-e" }
new_window = "C-n"
minimize_window = "W-Down"
snap_left = "W-Left"
snap_right = "W-Right"
maximize_window = "W-Up"
open_search = "W-s"
toggle_fullscreen = "F11"
lock_screen = [{ run = "rundll32.exe", args = ["user32.dll,LockWorkStation"] }]
screenshot_full = "W-PrintScreen"
vscode_command = ["C-S-p", { sleep = 50 }, { text = "{arg}" }, { sleep = 50 }, "Enter"]
split_window_right = { vscode = [{ call = "vscode_command", arg = "View: Split Editor Right" }], "*" = "snap_left" }
split_window_below = { vscode = [{ call = "vscode_command", arg = "View: Split Editor Down" }], "*" = "W-z" }
delete_other_windows = { vscode = [{ call = "vscode_command", arg = "View: Join All Editor Groups" }], "*" = "maximize_window" }
other_window = { vscode = [{ call = "vscode_command", arg = "View: Focus Next Editor Group" }], "*" = "switch_app" }
