include = ["default-actions.toml"]

[modifiers.Cmd]
key = "F19"
tap = ""
as = "C"

[keymap]
"Cmd-S-]" = "next_tab"
"Cmd-S-[" = "previous_tab"
C-Left = "previous_desktop"
C-Right = "next_desktop"
Cmd-Tab = { do = "switch_app", keep_mods = true }
Cmd-S-Tab = { do = "switch_app_back", keep_mods = true }
M-Tab = { do = "next_tab", keep_mods = true }
M-S-Tab = { do = "previous_tab", keep_mods = true }
C-Up = { do = "task_view", press = "tap" }
C-Down = { do = "show_desktop", press = "tap" }
Cmd-S-5 = { do = "screenshot", press = "tap" }
