//! Symbols per keyboard layout. The rows are generated by `gen-layouts.ps1` from the layouts
//! Windows ships: virtual key, the symbol it types alone, and the symbol it types with Shift.

/// Keyboard layout that symbol names (`;`, `$`, `ß`) are resolved against.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
pub enum Layout {
    #[default]
    Jis,
    Us,
    Uk,
    De,
    Fr,
}

impl Layout {
    pub const ALL: [Layout; 5] = [Layout::Jis, Layout::Us, Layout::Uk, Layout::De, Layout::Fr];

    /// Name used in the config (`"jis"`, `"us"`, ...).
    pub fn name(self) -> &'static str {
        match self {
            Layout::Jis => "jis",
            Layout::Us => "us",
            Layout::Uk => "uk",
            Layout::De => "de",
            Layout::Fr => "fr",
        }
    }

    pub fn from_name(name: &str) -> Option<Layout> {
        Self::ALL.into_iter().find(|l| l.name().eq_ignore_ascii_case(name))
    }

    pub(crate) fn rows(self) -> &'static [Row] {
        match self {
            Layout::Jis => JIS,
            Layout::Us => US,
            Layout::Uk => UK,
            Layout::De => DE,
            Layout::Fr => FR,
        }
    }
}

/// Virtual key, symbol typed alone, symbol typed with Shift (`""` = none).
pub(crate) type Row = (u8, &'static str, &'static str);

const JIS: &[Row] = &[
    (b'1', "", "!"),
    (b'2', "", "\""),
    (b'3', "", "#"),
    (b'4', "", "$"),
    (b'5', "", "%"),
    (b'6', "", "&"),
    (b'7', "", "'"),
    (b'8', "", "("),
    (b'9', "", ")"),
    (0xBA, ":", "*"),
    (0xBB, ";", "+"),
    (0xBC, ",", "<"),
    (0xBD, "-", "="),
    (0xBE, ".", ">"),
    (0xBF, "/", "?"),
    (0xC0, "@", "`"),
    (0xDB, "[", "{"),
    (0xDC, "\\", "|"),
    (0xDD, "]", "}"),
    (0xDE, "^", "~"),
    (0xE2, "\\", "_"),
];
const US: &[Row] = &[
    (b'0', "", ")"),
    (b'1', "", "!"),
    (b'2', "", "@"),
    (b'3', "", "#"),
    (b'4', "", "$"),
    (b'5', "", "%"),
    (b'6', "", "^"),
    (b'7', "", "&"),
    (b'8', "", "*"),
    (b'9', "", "("),
    (0xBA, ";", ":"),
    (0xBB, "=", "+"),
    (0xBC, ",", "<"),
    (0xBD, "-", "_"),
    (0xBE, ".", ">"),
    (0xBF, "/", "?"),
    (0xC0, "`", "~"),
    (0xDB, "[", "{"),
    (0xDC, "\\", "|"),
    (0xDD, "]", "}"),
    (0xDE, "'", "\""),
    (0xE2, "\\", "|"),
];
const UK: &[Row] = &[
    (b'0', "", ")"),
    (b'1', "", "!"),
    (b'2', "", "\""),
    (b'3', "", "£"),
    (b'4', "", "$"),
    (b'5', "", "%"),
    (b'6', "", "^"),
    (b'7', "", "&"),
    (b'8', "", "*"),
    (b'9', "", "("),
    (0xBA, ";", ":"),
    (0xBB, "=", "+"),
    (0xBC, ",", "<"),
    (0xBD, "-", "_"),
    (0xBE, ".", ">"),
    (0xBF, "/", "?"),
    (0xC0, "'", "@"),
    (0xDB, "[", "{"),
    (0xDC, "\\", "|"),
    (0xDD, "]", "}"),
    (0xDE, "#", "~"),
    (0xDF, "`", "¬"),
];
const DE: &[Row] = &[
    (b'0', "", "="),
    (b'1', "", "!"),
    (b'2', "", "\""),
    (b'3', "", "§"),
    (b'4', "", "$"),
    (b'5', "", "%"),
    (b'6', "", "&"),
    (b'7', "", "/"),
    (b'8', "", "("),
    (b'9', "", ")"),
    (0xBA, "ü", ""),
    (0xBB, "+", "*"),
    (0xBC, ",", ";"),
    (0xBD, "-", "_"),
    (0xBE, ".", ":"),
    (0xBF, "#", "'"),
    (0xC0, "ö", ""),
    (0xDB, "ß", "?"),
    (0xDC, "^", "°"),
    (0xDD, "´", "`"),
    (0xDE, "ä", ""),
    (0xE2, "<", ">"),
];
const FR: &[Row] = &[
    (b'0', "à", ""),
    (b'1', "&", ""),
    (b'2', "é", ""),
    (b'3', "\"", ""),
    (b'4', "'", ""),
    (b'5', "(", ""),
    (b'6', "-", ""),
    (b'7', "è", ""),
    (b'8', "_", ""),
    (b'9', "ç", ""),
    (0xBA, "$", "£"),
    (0xBB, "=", "+"),
    (0xBC, ",", "?"),
    (0xBE, ";", "."),
    (0xBF, ":", "/"),
    (0xC0, "ù", "%"),
    (0xDB, ")", "°"),
    (0xDC, "*", "µ"),
    (0xDD, "^", "¨"),
    (0xDE, "²", ""),
    (0xDF, "!", "§"),
    (0xE2, "<", ">"),
];
